# Generated by Django 5.1.5 on 2025-02-01 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casenum', models.CharField(max_length=8)),
                ('user', models.CharField(max_length=256)),
                ('claim_time', models.DateTimeField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
