# Generated by Django 5.1.5 on 2025-02-01 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('completeclaim', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completeclaim',
            old_name='creation_time',
            new_name='complete_time',
        ),
    ]
