# Generated by Django 5.2.1 on 2025-06-10 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('completeclaim', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='completeclaim',
            name='lead_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complete_lead', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='completeclaim',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complete_tech', to=settings.AUTH_USER_MODEL),
        ),
    ]
