version: '3.9'

services:
  web:
    build: .
    command: pipenv run daphne -b 0.0.0.0 -p 8000 api.asgi:application
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env