# Generated by Django 5.1.5 on 2025-02-01 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activeclaim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeclaim',
            name='casenum',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
