# Generated by Django 5.1.5 on 2025-02-01 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activeclaim', '0002_alter_activeclaim_casenum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activeclaim',
            old_name='creation_time',
            new_name='claim_time',
        ),
    ]
