# Generated by Django 5.1.7 on 2025-03-25 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activeclaim', '0004_alter_activeclaim_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activeclaim',
            old_name='user',
            new_name='user_id',
        ),
    ]
