# Generated by Django 5.1.5 on 2025-02-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewedClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casenum', models.CharField(max_length=8)),
                ('tech', models.CharField(max_length=256)),
                ('lead', models.CharField(max_length=256)),
                ('claim_time', models.DateTimeField()),
                ('complete_time', models.DateTimeField()),
                ('review_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('checked', 'Checked'), ('done', 'Done'), ('pingedlow', 'Pinged - Low'), ('pingedmed', 'Pinged - Medium'), ('pingedhigh', 'Pinged - High'), ('resolved', 'Resolved'), ('kudos', 'Kudos')], max_length=255)),
                ('comment', models.TextField()),
            ],
        ),
    ]
