# Generated by Django 5.1.7 on 2025-04-16 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewedClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casenum', models.CharField(max_length=8)),
                ('claim_time', models.DateTimeField()),
                ('complete_time', models.DateTimeField()),
                ('review_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('checked', 'Checked'), ('done', 'Done'), ('pingedlow', 'Pinged - Low'), ('pingedmed', 'Pinged - Medium'), ('pingedhigh', 'Pinged - High'), ('resolved', 'Resolved'), ('kudos', 'Kudos')], max_length=255)),
                ('comment', models.TextField()),
                ('lead_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead', to=settings.AUTH_USER_MODEL)),
                ('tech_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
