# Generated by Django 5.1.5 on 2025-02-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewedclaim', '0003_alter_reviewedclaim_lead_alter_reviewedclaim_tech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewedclaim',
            name='lead',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reviewedclaim',
            name='tech',
            field=models.IntegerField(),
        ),
    ]
