# Generated by Django 5.1.7 on 2025-04-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parentcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentcase',
            name='case_number',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
